export enum CardName {
  jackOfHearts = 'jackOfHearts',
  nineOfHearts = 'nineOfHearts',
  aceOfHearts = 'aceOfHearts',
  tenOfHearts = 'tenOfHearts',
  kingOfHearts = 'kingOfHearts',
  queenOfHearts = 'queenOfHearts',
  eightOfHearts = 'eightOfHearts',
  sevenOfHearts = 'sevenOfHearts',
  jackOfClubs = 'jackOfClubs',
  nineOfClubs = 'nineOfClubs',
  aceOfClubs = 'aceOfClubs',
  tenOfClubs = 'tenOfClubs',
  kingOfClubs = 'kingOfClubs',
  queenOfClubs = 'queenOfClubs',
  eightOfClubs = 'eightOfClubs',
  sevenOfClubs = 'sevenOfClubs',
  jackOfSpades = 'jackOfSpades',
  nineOfSpades = 'nineOfSpades',
  aceOfSpades = 'aceOfSpades',
  tenOfSpades = 'tenOfSpades',
  kingOfSpades = 'kingOfSpades',
  queenOfSpades = 'queenOfSpades',
  eightOfSpades = 'eightOfSpades',
  sevenOfSpades = 'sevenOfSpades',
  jackOfDiamonds = 'jackOfDiamonds',
  nineOfDiamonds = 'nineOfDiamonds',
  aceOfDiamonds = 'aceOfDiamonds',
  tenOfDiamonds = 'tenOfDiamonds',
  kingOfDiamonds = 'kingOfDiamonds',
  queenOfDiamonds = 'queenOfDiamonds',
  eightOfDiamonds = 'eightOfDiamonds',
  sevenOfDiamonds = 'sevenOfDiamonds',
}

export interface CardStructure {
  name: CardName;
  type: string;
  precedence: number;
  number: number;
  weight: number;
  image: string;
  alt: string;
  isShow: boolean;
  isPicked: boolean;
}

export const cards = {
  [CardName.jackOfHearts]: {
    name: CardName.jackOfHearts,
    type: 'hearts',
    precedence: 8,
    number: 11,
    weight: 3,
    image: '/cards/jack_of_hearts.png',
    alt: 'jack of hearts',
    isShow: false,
    isPicked: false,
  },
  [CardName.nineOfHearts]: {
    name: CardName.nineOfHearts,
    type: 'hearts',
    precedence: 7,
    number: 9,
    weight: 2,
    image: '/cards/9_of_hearts.png',
    alt: 'nine of hearts',
    isShow: false,
    isPicked: false,
  },
  [CardName.aceOfHearts]: {
    name: CardName.aceOfHearts,
    type: 'hearts',
    precedence: 6,
    number: 14,
    weight: 1,
    image: '/cards/ace_of_hearts.png',
    alt: 'ace of hearts',
    isShow: false,
    isPicked: false,
  },
  [CardName.tenOfHearts]: {
    name: CardName.tenOfHearts,
    type: 'hearts',
    precedence: 5,
    number: 10,
    weight: 1,
    image: '/cards/10_of_hearts.png',
    alt: 'ten of hearts',
    isShow: false,
    isPicked: false,
  },
  [CardName.kingOfHearts]: {
    name: CardName.kingOfHearts,
    type: 'hearts',
    precedence: 4,
    number: 13,
    weight: 0,
    image: '/cards/king_of_hearts.png',
    alt: 'king of hearts',
    isShow: false,
    isPicked: false,
  },
  [CardName.queenOfHearts]: {
    name: CardName.queenOfHearts,
    type: 'hearts',
    precedence: 3,
    number: 12,
    weight: 0,
    image: '/cards/queen_of_hearts.png',
    alt: 'queen of hearts',
    isShow: false,
    isPicked: false,
  },
  [CardName.eightOfHearts]: {
    name: CardName.eightOfHearts,
    type: 'hearts',
    precedence: 2,
    number: 8,
    weight: 0,
    image: '/cards/8_of_hearts.png',
    alt: 'eight of hearts',
    isShow: false,
    isPicked: false,
  },
  [CardName.sevenOfHearts]: {
    name: CardName.sevenOfHearts,
    type: 'hearts',
    precedence: 1,
    number: 7,
    weight: 0,
    image: '/cards/7_of_hearts.png',
    alt: 'seven of hearts',
    isShow: false,
    isPicked: false,
  },

  [CardName.jackOfClubs]: {
    name: CardName.jackOfClubs,
    type: 'clubs',
    precedence: 8,
    number: 11,
    weight: 3,
    image: '/cards/jack_of_clubs.png',
    alt: 'jack of clubs',
    isShow: false,
    isPicked: false,
  },
  [CardName.nineOfClubs]: {
    name: CardName.nineOfClubs,
    type: 'clubs',
    precedence: 7,
    number: 9,
    weight: 2,
    image: '/cards/9_of_clubs.png',
    alt: 'nine of Clubs',
    isShow: false,
    isPicked: false,
  },
  [CardName.aceOfClubs]: {
    name: CardName.aceOfClubs,
    type: 'clubs',
    precedence: 6,
    number: 14,
    weight: 1,
    image: '/cards/ace_of_clubs.png',
    alt: 'ace of Clubs',
    isShow: false,
    isPicked: false,
  },
  [CardName.tenOfClubs]: {
    name: CardName.tenOfClubs,
    type: 'clubs',
    precedence: 5,
    number: 10,
    weight: 1,
    image: '/cards/10_of_clubs.png',
    alt: 'ten of Clubs',
    isShow: false,
    isPicked: false,
  },
  [CardName.kingOfClubs]: {
    name: CardName.kingOfClubs,
    type: 'clubs',
    precedence: 4,
    number: 13,
    weight: 0,
    image: '/cards/king_of_clubs.png',
    alt: 'king of clubs',
    isShow: false,
    isPicked: false,
  },
  [CardName.queenOfClubs]: {
    name: CardName.queenOfClubs,
    type: 'clubs',
    precedence: 3,
    number: 12,
    weight: 0,
    image: '/cards/queen_of_clubs.png',
    alt: 'queen of Clubs',
    isShow: false,
    isPicked: false,
  },
  [CardName.eightOfClubs]: {
    name: CardName.eightOfClubs,
    type: 'clubs',
    precedence: 2,
    number: 8,
    weight: 0,
    image: '/cards/8_of_clubs.png',
    alt: 'eight of clubs',
    isShow: false,
    isPicked: false,
  },
  [CardName.sevenOfClubs]: {
    name: CardName.sevenOfClubs,
    type: 'clubs',
    precedence: 1,
    number: 7,
    weight: 0,
    image: '/cards/7_of_clubs.png',
    alt: 'seven of clubs',
    isShow: false,
    isPicked: false,
  },
  [CardName.jackOfSpades]: {
    name: CardName.jackOfSpades,
    type: 'spades',
    precedence: 8,
    number: 11,
    weight: 3,
    image: '/cards/jack_of_spades.png',
    alt: 'jack of Spades',
    isShow: false,
    isPicked: false,
  },
  [CardName.nineOfSpades]: {
    name: CardName.nineOfSpades,
    type: 'spades',
    precedence: 7,
    number: 9,
    weight: 2,
    image: '/cards/9_of_spades.png',
    alt: 'nine of Spades',
    isShow: false,
    isPicked: false,
  },
  [CardName.aceOfSpades]: {
    name: CardName.aceOfSpades,
    type: 'spades',
    precedence: 6,
    number: 14,
    weight: 1,
    image: '/cards/ace_of_spades.png',
    alt: 'ace of Spades',
    isShow: false,
    isPicked: false,
  },
  [CardName.tenOfSpades]: {
    name: CardName.tenOfSpades,
    type: 'spades',
    precedence: 5,
    number: 10,
    weight: 1,
    image: '/cards/10_of_spades.png',
    alt: 'ten of Spades',
    isShow: false,
    isPicked: false,
  },
  [CardName.kingOfSpades]: {
    name: CardName.kingOfSpades,
    type: 'spades',
    precedence: 4,
    number: 13,
    weight: 0,
    image: '/cards/king_of_spades.png',
    alt: 'king of Spades',
    isShow: false,
    isPicked: false,
  },
  [CardName.queenOfSpades]: {
    name: CardName.queenOfSpades,
    type: 'spades',
    precedence: 3,
    number: 12,
    weight: 0,
    image: '/cards/queen_of_spades.png',
    alt: 'queen of Spades',
    isShow: false,
    isPicked: false,
  },
  [CardName.eightOfSpades]: {
    name: CardName.eightOfSpades,
    type: 'spades',
    precedence: 2,
    number: 8,
    weight: 0,
    image: '/cards/8_of_spades.png',
    alt: 'eight of Spades',
    isShow: false,
    isPicked: false,
  },
  [CardName.sevenOfSpades]: {
    name: CardName.sevenOfSpades,
    type: 'spades',
    precedence: 1,
    number: 7,
    weight: 0,
    image: '/cards/7_of_spades.png',
    alt: 'seven of Spades',
    isShow: false,
    isPicked: false,
  },
  [CardName.jackOfDiamonds]: {
    name: CardName.jackOfDiamonds,
    type: 'diamonds',
    precedence: 8,
    number: 11,
    weight: 3,
    image: '/cards/jack_of_diamonds.png',
    alt: 'jack of Diamonds',
    isShow: false,
    isPicked: false,
  },
  [CardName.nineOfDiamonds]: {
    name: CardName.nineOfDiamonds,
    type: 'diamonds',
    precedence: 7,
    number: 9,
    weight: 2,
    image: '/cards/9_of_diamonds.png',
    alt: 'nine of Diamonds',
    isShow: false,
    isPicked: false,
  },
  [CardName.aceOfDiamonds]: {
    name: CardName.aceOfDiamonds,
    type: 'diamonds',
    precedence: 6,
    number: 14,
    weight: 1,
    image: '/cards/ace_of_diamonds.png',
    alt: 'ace of Diamonds',
    isShow: false,
    isPicked: false,
  },
  [CardName.tenOfDiamonds]: {
    name: CardName.tenOfDiamonds,
    type: 'diamonds',
    precedence: 5,
    number: 10,
    weight: 1,
    image: '/cards/10_of_diamonds.png',
    alt: 'ten of Diamonds',
    isShow: false,
    isPicked: false,
  },
  [CardName.kingOfDiamonds]: {
    name: CardName.kingOfDiamonds,
    type: 'diamonds',
    precedence: 4,
    number: 13,
    weight: 0,
    image: '/cards/king_of_diamonds.png',
    alt: 'king of Diamonds',
    isShow: false,
    isPicked: false,
  },
  [CardName.queenOfDiamonds]: {
    name: CardName.queenOfDiamonds,
    type: 'diamonds',
    precedence: 3,
    number: 12,
    weight: 0,
    image: '/cards/queen_of_diamonds.png',
    alt: 'queen of Diamonds',
    isShow: false,
    isPicked: false,
  },
  [CardName.eightOfDiamonds]: {
    name: CardName.eightOfDiamonds,
    type: 'diamonds',
    precedence: 2,
    number: 8,
    weight: 0,
    image: '/cards/8_of_diamonds.png',
    alt: 'eight of Diamonds',
    isShow: false,
    isPicked: false,
  },
  [CardName.sevenOfDiamonds]: {
    name: CardName.sevenOfDiamonds,
    type: 'diamonds',
    precedence: 1,
    number: 7,
    weight: 0,
    image: '/cards/7_of_diamonds.png',
    alt: 'seven of Diamonds',
    isShow: false,
    isPicked: false,
  },
};
